language: node_js

sudo: false

jobs:
  include:
    - os: linux
      dist: trusty
    - os: osx

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
  - npm version
  - npm run vscode:prepublish

script:
  - npm test --silent
  