version: 2.1

jobs:
  build-test:
    machine:
      image: linux-cuda:edge
    steps:
      - checkout
      - run:
          name: Install NPM packages
          command: npm install
      - run:
          name: Show NPM version
          command: npm version
      - run:
          name: Build extension
          command: npm run vscode:prepublish
      - run:
          name: Run tests
          command: npm test

workflows:
  build-test-workflow:
    jobs:
      - build-test
